services:
  used-car-marketplace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7856:7856"
    environment:
      - NODE_ENV=production
      - PORT=7856
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7856/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - used-car-network

networks:
  used-car-network:
    driver: bridge 